services:
#  goapp:
#    build: .
#    container_name: dbmt
#    ports:
#      - "5461:5461"
#    environment:
#      CREDS_SUBDIR: credentials
#    volumes:
#      - ./docker:/usr/src/app/credentials

  oracle-xe:
    image: gvenzl/oracle-free:23-slim
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: sys_pass
      APP_USER: appuser 
      APP_USER_PASSWORD: appuser_pass
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
      start_interval: 5s
    restart: unless-stopped
